version: "3"

services:
  redis-master:
    image: 'bitnami/redis:latest'
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"

  redis-sentinel:
    image: 'bitnami/redis-sentinel:latest'
    depends_on:
      - redis-master
    environment:
      REDIS_MASTER_SET: "redis-master"
      REDIS_MASTER_HOST: "redis-master"

  app:
    image: ${DOCKER_REPOSITORY}/${APP_NAME}:${VERSION}
    depends_on:
      - redis-sentinel
    env_file:
      - ./config/env.dev
    deploy:
      replicas: ${REPLICAS_COUNT:-1}